### ISSUE TITLE
What is the correct `commandBuffer` parameter for `vkBeginCommandBuffer`?

### ISSUE THREAD

**Issue by sunbearc22** [realitix/vulkan#49]
Hi realitx, I got a Python `TypeError` at `vkBeginCommandBuffer` when trying to copy a staging buffer to a vertex buffer. 
```
 allocInfo =  <cdata 'struct VkCommandBufferAllocateInfo' owning 32 bytes>
self.commandBuffer_transfer =  <cdata 'struct VkCommandBuffer_T *[1]' owning 8 bytes>

Traceback (most recent call last):
  File "~/6_staging_buffer/application_v6_staging_buffer.py", line 227, in <module>
    main()
  File "~/6_staging_buffer/application_v6_staging_buffer.py", line 209, in main
    vulkanbase = initVulkan(window, debug=debug, vertices=vertices)
  File "~/6_staging_buffer/application_v6_staging_buffer.py", line 35, in initVulkan
    return vulkanbase.Setup(window, debug, vertices)
  File "~/6_staging_buffer/vulkanbase_v6_staging_buffer.py", line 214, in __init__
    self.createVertexBuffer()  #New
  File "~/6_staging_buffer/vulkanbase_v6_staging_buffer.py", line 1665, in createVertexBuffer
    self.copyBuffer(self.stagingBuffer, self.vertexBuffer, buffersize)
  File "~/6_staging_buffer/vulkanbase_v6_staging_buffer.py", line 1695, in copyBuffer
    vkBeginCommandBuffer(self.commandBuffer_transfer, beginInfo)
  File "~/.local/lib/python3.5/site-packages/vulkan/_vulkan.py", line 4572, in vkBeginCommandBuffer
    result = _callApi(lib.vkBeginCommandBuffer, commandBuffer,pBeginInfo)
  File "~/.local/lib/python3.5/site-packages/vulkan/_vulkan.py", line 3573, in _callApi
    return fn(*fn_args)
TypeError: initializer for ctype 'struct VkCommandBuffer_T *' must be a pointer to same type, not cdata 'struct VkCommandBuffer_T *[1]'
```
It seems that the `commandBuffer` parameter I had passed to `vkBeginCommandBuffer` is the wrong type. I don't know why this is the case. The 'vkBeginCommandBuffer' occurred in my `copyBuffer` method is given below. 
```
    def copyBuffer(self, srcBuffer, dstBuffer, size):
        logging.info('')
        logging.info('  -- Copy Buffer to Another Buffer:')
        allocInfo = VkCommandBufferAllocateInfo(
            level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
            commandPool = self.command_pool_transfer,
            #commandPool = self.command_pool,
            commandBufferCount = 1,)
        logging.info('    - set allocInfo.')
        print('allocInfo = ', allocInfo)
        self.commandBuffer_transfer = vkAllocateCommandBuffers(
            self.logical_device, allocInfo)
        logging.info('    - created commandBuffer_transfer.')
        print('self.commandBuffer_transfer = ', self.commandBuffer_transfer)

        beginInfo = VkCommandBufferBeginInfo(
            flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT)
        logging.info('    - set CommandBufferBeginInfo.')
        

        vkBeginCommandBuffer(self.commandBuffer_transfer, beginInfo)
        logging.info('    - vkBeginCommandBuffer.')
        copyRegion = [ VkBufferCopy( srcOffset = 0,
                                     dstOffest = 0,
                                     size = size) ]
        logging.info('    - copyRegion.')
        vkCmdCopyBuffer( self.commandBuffer_transfer, srcBuffer, dstBuffer,
                         len(copyRegion), copyRegion )
        logging.info('    - vkCmdCopyBuffer.')
        vkEndCommandBuffer(self.commandBuffer_transfer)
        logging.info('    - vkEndCommandBuffer.')


        submitInfo = VkSubmitInfo(
            commandBufferCount = 1,
            pCommandBuffers = self.commandBuffer_transfer )
        logging.info('    - set submitInfo.')

        vkQueueSubmit( self.transfer_queue, 1, submitInfo, VK_NULL_HANDLE)
        logging.info('    - vkQueueSubmit.')
        vkQueueWaitIdle( self.transfer_queue )

        vkFreeCommandBuffers( self.logical_device, self.commandPool_transfer, 1,
                              self.commandBuffer_transfer )
        logging.info('    - free Transfer vkQueueSubmit.')
```
Referring to Vulk, I noticed you put `self.commandBuffer_transfer` into a [list](https://github.com/realitix/vulk/blob/master/vulk/vulkanobject.py#L1187). So I made the following changes:
```
        vkBeginCommandBuffer([self.commandBuffer_transfer], beginInfo)
```
However, I now get a Python `ValueError`:
```
  File "~/6_staging_buffer/vulkanbase_v6_staging_buffer.py", line 1697, in copyBuffer
    vkBeginCommandBuffer([self.commandBuffer_transfer], beginInfo)
  File "~/.local/lib/python3.5/site-packages/vulkan/_vulkan.py", line 4572, in vkBeginCommandBuffer
    result = _callApi(lib.vkBeginCommandBuffer, commandBuffer,pBeginInfo)
  File "~/.local/lib/python3.5/site-packages/vulkan/_vulkan.py", line 3572, in _callApi
    fn_args = [_auto_handle(i, j) for i, j in zip(args, ffi.typeof(fn).args)]
  File "~/.local/lib/python3.5/site-packages/vulkan/_vulkan.py", line 3572, in <listcomp>
    fn_args = [_auto_handle(i, j) for i, j in zip(args, ffi.typeof(fn).args)]
  File "~/.local/lib/python3.5/site-packages/vulkan/_vulkan.py", line 3566, in _auto_handle
    ptr, _ = _cast_ptr(x, _type)
  File "~/.local/lib/python3.5/site-packages/vulkan/_vulkan.py", line 90, in _cast_ptr3
    return _cast_ptr2(x, _type)
  File "~/.local/lib/python3.5/site-packages/vulkan/_vulkan.py", line 80, in _cast_ptr2
    ret = ffi.new(_type.item.cname+'[]', x)
ValueError: array item of unknown size: 'struct VkCommandBuffer_T' 
```
Can you advice me what i am doing wrong and what is the correct way to write this part? Thanks.

**Comment by sunbearc22** [comment]
Hi realitix, thanks. Since 'self.commandBuffer_transfer' is a list,  I did a for-loop to pass its elements to commands from `vkBeginCommandBuffer`  to `vkEndCommandBuffer`, and it worked. :)

```
    def copyBuffer(self, srcBuffer, dstBuffer, size):
        logging.info('')
        logging.info('  -- Copy Buffer to Another Buffer:')
        
        allocInfo = VkCommandBufferAllocateInfo(
            level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
            commandPool = self.command_pool_transfer,
            #commandPool = self.command_pool,
            commandBufferCount = 1,)
        logging.info('    - set allocInfo.')
        print('allocInfo = ', allocInfo)

        self.commandBuffer_transfer = \
            vkAllocateCommandBuffers(self.logical_device, allocInfo)
        logging.info('    - created commandBuffer_transfer.')
        print('self.commandBuffer_transfer = ', self.commandBuffer_transfer)

        beginInfo = VkCommandBufferBeginInfo(
            flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT)
        logging.info('    - set CommandBufferBeginInfo.')
        

        for command_buffer in self.commandBuffer_transfer:
            
            vkBeginCommandBuffer(command_buffer, beginInfo)
            logging.info('    - vkBeginCommandBuffer.')
            copyRegion = [ VkBufferCopy( srcOffset = 0,
                                         dstOffset = 0,
                                         size = size) ]
            logging.info('    - copyRegion.')
            vkCmdCopyBuffer( command_buffer, srcBuffer, dstBuffer,
                             len(copyRegion), copyRegion )
            logging.info('    - vkCmdCopyBuffer.')
            vkEndCommandBuffer(command_buffer)
            logging.info('    - vkEndCommandBuffer.')


        submitInfo = VkSubmitInfo(
            commandBufferCount = 1,
            pCommandBuffers = self.commandBuffer_transfer )
        logging.info('    - set submitInfo.')

        vkQueueSubmit( self.transfer_queue, 1, submitInfo, VK_NULL_HANDLE)
        logging.info('    - vkQueueSubmit.')
        vkQueueWaitIdle( self.transfer_queue )

        vkFreeCommandBuffers( self.logical_device, self.command_pool_transfer, 1,
                              self.commandBuffer_transfer )
        logging.info('    - free Transfer vkQueueSubmit.')
```
