### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by okuma10** [realitix/vulkan#60]
Both pip and manual install gives me this error.

`WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
  ERROR: Command errored out with exit status 1:
   command: 'D:\Nikola\Python\Projects\10RealWorldApps\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Okuma_10\\AppData\\Local\\Temp\\pip-wheel-tekhmmz1\\pycparser\\setup.py'"'"'; __file__='"'"'C:\\Users\\Okuma_10\\AppD
ata\\Local\\Temp\\pip-wheel-tekhmmz1\\pycparser\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Okuma_10\AppData\Lo
cal\Temp\pip-wheel-fasnoyy2'
       cwd: C:\Users\Okuma_10\AppData\Local\Temp\pip-wheel-tekhmmz1\pycparser\
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for pycparser
ERROR: Failed to build one or more wheels
Traceback (most recent call last):
  File "D:\Nikola\Python\Projects\10RealWorldApps\venv\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "C:\Users\Okuma_10\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:\\Nikola\\Python\\Projects\\10RealWorldApps\\venv\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Okuma_10\\AppData\\Local\\Temp\\tmpeus9tyww', '--quiet', 'pycparser
']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    cffi_modules=["vulkan/vulkan_build.py:ffi"]
  File "D:\Nikola\Python\Projects\10RealWorldApps\venv\lib\site-packages\setuptools\__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "D:\Nikola\Python\Projects\10RealWorldApps\venv\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "D:\Nikola\Python\Projects\10RealWorldApps\venv\lib\site-packages\setuptools\dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "D:\Nikola\Python\Projects\10RealWorldApps\venv\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "D:\Nikola\Python\Projects\10RealWorldApps\venv\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "D:\Nikola\Python\Projects\10RealWorldApps\venv\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
    return installer(requirement)
  File "D:\Nikola\Python\Projects\10RealWorldApps\venv\lib\site-packages\setuptools\dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "D:\Nikola\Python\Projects\10RealWorldApps\venv\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['D:\\Nikola\\Python\\Projects\\10RealWorldApps\\venv\\Scripts\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Okuma_10\\AppData\\Local\\Temp\\tmpeus9tyww', '--quiet', 'pycpars
er']' returned non-zero exit status 1.
`

**Comment by okuma10** [comment]
I guess the issue was with 'pycparser' module.
It had to be installed to work.

**Comment by realitix** [comment]
Hello, Pycparser is a dependancy of cffi so you shouldn't need to install it manually, strange...
