### ISSUE TITLE
Cannot run example shown in readme

### ISSUE THREAD

**Issue by shadow7412** [realitix/vulkan#84]
I get the following stack trace when attempting to run example_sdl2.py;

```
Traceback (most recent call last):
  File "./vulkan_test/vulkan/v2/example/example_sdl2.py", line 38, in <module>
    appInfo = VkApplicationInfo(
  File "./vulkan_test/venv/lib/python3.10/site-packages/vulkan/_vulkan.py", line 3079, in VkApplicationInfo
    return _new('VkApplicationInfo', sType=sType,pNext=pNext,pApplicationName=pApplicationName,applicationVersion=applicationVersion,pEngineName=pEngineName,engineVersion=engineVersion,apiVersion=apiVersion)
  File "./vulkan_test/venv/lib/python3.10/site-packages/vulkan/_vulkan.py", line 3007, in _new
    ptrs[k] = _cast_ptr(v, ktype)
  File "./vulkan_test/venv/lib/python3.10/site-packages/vulkan/_vulkan.py", line 90, in _cast_ptr3
    return _cast_ptr2(x, _type)
  File "./vulkan_test/venv/lib/python3.10/site-packages/vulkan/_vulkan.py", line 74, in _cast_ptr2
    if isinstance(x, _collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'
```

Could it be that python 3.10 isn't supported yet?

**Comment by shadow7412** [comment]
Looks like merging #83 should fix this.

**Comment by realitix** [comment]
It's fixed
