### ISSUE TITLE
Import vulkan failed on Mac.

### ISSUE THREAD

**Issue by BelconZhao** [realitix/vulkan#91]
I tried to learn vukan today with my Macbook. I installed SDK (vulkansdk-macos-1.3.283.0.dmg). I also installed vulkan module via pip. You can check my output attached as below. But I got "Cannot find Vulkan sDK version" error when I import vulkan module. The error happened when python tried to load dynamic library. I checked with module cffi and found it worked fine. That means this issue is not related to the path.

Any suggestions? Thanks a lot.

`(.venv) zhaob@C02GC2VUMD6T vulkan % pip list
Package   Version
--------- ---------
cffi      1.16.0
glfw      2.7.0
pip       24.0
pycparser 2.22
vulkan    1.3.275.1
(.venv) zhaob@C02GC2VUMD6T vulkan % python3 -m "import vulkan"
/Users/belconzhao/Study/python/Vulkan/vulkan_tutorial/.venv/bin/python3: No module named import vulkan
(.venv) zhaob@C02GC2VUMD6T vulkan % python3 -c "import vulkan"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/belconzhao/Study/python/Vulkan/vulkan_tutorial/.venv/lib/python3.12/site-packages/vulkan/__init__.py", line 1, in <module>
    from vulkan._vulkan import * # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/belconzhao/Study/python/Vulkan/vulkan_tutorial/.venv/lib/python3.12/site-packages/vulkan/_vulkan.py", line 111, in <module>
    raise OSError('Cannot find Vulkan SDK version. Please ensure that it is '
OSError: Cannot find Vulkan SDK version. Please ensure that it is installed and that the <sdk_root>/<version>/lib/ folder is in the library path
(.venv) zhaob@C02GC2VUMD6T vulkan % python3 - <<EOF           
heredoc> import cffi
heredoc> ffi = cffi.FFI()
heredoc> lib = ffi.dlopen('libvulkan.dylib')
heredoc> print(f'{lib}')
heredoc> ffi.dlclose(lib)
heredoc> EOF
<cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x10d98e960>
(.venv) zhaob@C02GC2VUMD6T vulkan % 
`

**Comment by junqingqiao** [comment]
I'm experiencing the same

**Comment by jmacey** [comment]
I have a fix for this, if you edit the _vulkan.py file (line 103 on my version) and hard code the path it will find it and load it. 

```
# Load SDK
_lib_names = ('libvulkan.so.1', 'vulkan-1.dll', 'libvulkan.dylib',"/usr/local/lib/libvulkan.dylib")
```

You also need to set the envars (I'm on latest version)

```
export VK_ICD_FILENAMES=/usr/local/share/vulkan/icd.d/MoltenVK_icd.json
export VK_LAYER_PATH=/usr/local/share/vulkan/explicit_layer.d
```

Only came here to see if there were any pull requests for this, I think what is happening is the mac SIP is not allowing the search for the DYLD_LIBRARY_PATH so the loading is failing.  Not sure if the project is alive anymore.

**Comment by MarcWeber** [comment]
cpp -> ```clang -E```  in generate.py ? THen add
```
               '-DVK_USE_PLATFORM_METAL_EXT',
```

Then python generate/generate.py works.
Then you can ```pip install .```
Then the sample actually runs with some modifications:.
The portability extensions etc should be conditional thus cleaned up maybe sys.patform == "darwin" and silicon chip ..
Maybe there is a way to make Vulkan config pass it automatically ..

```
index c81386c..392c961 100644
--- a/example/example_sdl2.py
+++ b/example/example_sdl2.py
@@ -4,6 +4,7 @@
 
 # flake8: noqa
 import ctypes
+import platform
 import os
 import sdl2
 import sdl2.ext
@@ -70,10 +71,13 @@ elif wm_info.subsystem == sdl2.SDL_SYSWM_COCOA:
 else:
     raise Exception("Platform not supported")
 
-# extensions.append("VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME")
-extensions.append("VK_KHR_portability_enumeration")
-extensions.append("VK_KHR_surface")
-extensions.append("VK_EXT_metal_surface")
+is_apple_silicon = platform.system() == "Darwin" and platform.machine() == "arm64"
+
+if is_apple_silicon:
+    # extensions.append("VK_KHR_PORTABILITY_ENUMERATION_EXTENSION_NAME")
+    extensions.append("VK_KHR_portability_enumeration")
+    extensions.append("VK_KHR_surface")
+    extensions.append("VK_EXT_metal_surface")
 
 createInfo = VkInstanceCreateInfo(
     sType=VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
@@ -83,7 +87,8 @@ createInfo = VkInstanceCreateInfo(
     ppEnabledExtensionNames=extensions,
     enabledLayerCount=len(layers),
     ppEnabledLayerNames=layers)
-createInfo.flags |= VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR
+if is_apple_silicon:
+    createInfo.flags |= VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR
 
 instance = vkCreateInstance(createInfo, None)
 
@@ -241,8 +246,8 @@ queues_create = [VkDeviceQueueCreateInfo(sType=VK_STRUCTURE_TYPE_DEVICE_QUEUE_CR
                                          flags=0)
                  for i in {queue_family_graphic_index,
                            queue_family_present_index}]
-
-extensions.append("VK_KHR_portability_subset")
+if is_apple_silicon:
+    extensions.append("VK_KHR_portability_subset")
 
 device_create = VkDeviceCreateInfo(
     sType=VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
```

**Comment by realitix** [comment]
Hello, can you ask Claude to find the bug and to fix it ? Then send me the PR. I don't have a mac so i can't fix it

**Comment by MarcWeber** [comment]
There is no bug. The triangle appears with the -D* argument when regenerating the vulkan.cdef.h file . No idea whether more complex examples work yet. That's why I only commented on this issue, yet.  Will be doing more more experiments later.
